In [1]:
#1. Fundamentos de NumPy
import numpy as np #n = numerico, py = python
import pandas as pd

In [2]:
#b. leer datos
df = pd.read_csv("Ciudades_Visitadas_Latinoamerica_2023.csv")
df

Ciudad       País  Población  Visitantes
0   Ciudad de México     México    9265833    21000000
1       Buenos Aires  Argentina    3059574    15000000
2     Río de Janeiro     Brasil    6748314    13000000
3               Lima       Perú    9756020     9000000
4             Bogotá   Colombia    7181663     8000000
5  Santiago de Chile      Chile    6199241     7500000
6          São Paulo     Brasil   12333146    20000000
7          La Habana       Cuba    2164182     4000000
8             Cancún     México     888124     5000000
9          Cartagena   Colombia    1036671     3000000

In [3]:
#b. 
df["Población"].mean()

5863276.8

In [4]:
#c. redondear el promedio numpy
np.round(df["Población"].mean())

5863277.0

In [5]:
#d.
np.min(df["Visitantes"])

3000000

In [6]:
#2. Arrays con Numpy
#a. Crear arrays
mi_array = np.array([1,2,3,4,5])
mi_array

array([1, 2, 3, 4, 5])

In [7]:
type(mi_array)

numpy.ndarray

In [8]:
#Id. la dimension del array
len(mi_array)

5

In [9]:
#b. Crear array de 2 dimensiones
array_2d = np.array([[1,2,3],[4,5,6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
type(array_2d)

numpy.ndarray

In [11]:
len(array_2d)

2

In [12]:
#3. Manipular Arrays
#a. concatenar (Juntar, unir arrays)
#Crear 3 listas
x = [1,2,3]
y = [1,2,3]
z = [1,2,3]

In [13]:
#unir las listas con numpy
np.concatenate([x,y,z])

array([1, 2, 3, 1, 2, 3, 1, 2, 3])