# Arboles de Decision Parte 2

* Sobreajuste en los árboles de decisión
* Poda de árboles de decisión
* Simplificación de árboles de decisión mediante poda (algoritmo C4.5)
* Algoritmo CART
* Ejemplos prácticos

### Sobreajuste en los árboles de decisión

![Overfitting](https://th.bing.com/th/id/R.5eb443c8ed7b35464b02a1da6087c5a7?rik=5suy7VEr1BDSpg&pid=ImgRaw&r=0&sres=1&sresct=1)

### Poda de árboles de decisión

![Poda](https://th.bing.com/th/id/R.9b1cd84213c7057f0c93e2003ef41138?rik=vLtyz4SG4GUAsA&pid=ImgRaw&r=0&sres=1&sresct=1)

### Simplificación de árboles de decisión mediante poda (algoritmo C4.5)

![C4.5](https://www.researchgate.net/publication/319475730/figure/fig2/AS:535048409812992@1504576889684/Figura-2-Arvore-de-decisao-utilizando-o-algoritmo-C45.png)

### Algoritmo CART

![CART](CART.png)

### Ejemplos prácticos

#### Caso 1: Clasificación

In [1]:
import pandas as pd
import numpy as np

In [ ]:
clasificacion = pd.read_csv("./Data/ML-MATT-CompetitionQT2021_train.csv", sep = ";")
clasificacion.head()

,Time,CellName,PRBUsageUL,PRBUsageDL,meanThr_DL,meanThr_UL,maxThr_DL,maxThr_UL,meanUE_DL,meanUE_UL,maxUE_DL,maxUE_UL,maxUE_UL+DL,Unusual
0,10:45,3BLTE,12.3848,1.4019,0.3927,0.0438,16.6522,0.6806,1.1293,1.0491,5,3,8,1
1,9:45,1BLTE,22.0438,2.0016,0.5620,0.2697,10.3994,1.1771,1.4480,1.1630,6,5,11,1
2,7:45,9BLTE,0.5105,0.4258,0.0152,0.0106,0.2755,0.1685,1.0379,1.0535,1,2,3,1
3,2:45,4ALTE,1.9963,1.1513,0.9908,0.0245,64.7465,0.8747,1.0766,1.0526,3,2,5,1
4,3:30,10BLTE,0.3030,0.4040,0.0160,0.0130,0.3480,0.1680,1.0110,1.0110,2,1,3,0


In [3]:
data = clasificacion[['PRBUsageUL', 'PRBUsageDL', 'meanThr_DL',
       'meanThr_UL', 'maxThr_DL', 'maxThr_UL', 'meanUE_DL', 'meanUE_UL',
       'maxUE_DL', 'maxUE_UL', 'maxUE_UL+DL', 'Unusual']]
data.head()

,PRBUsageUL,PRBUsageDL,meanThr_DL,meanThr_UL,maxThr_DL,maxThr_UL,meanUE_DL,meanUE_UL,maxUE_DL,maxUE_UL,maxUE_UL+DL,Unusual
0,12.3848,1.4019,0.3927,0.0438,16.6522,0.6806,1.1293,1.0491,5,3,8,1
1,22.0438,2.0016,0.5620,0.2697,10.3994,1.1771,1.4480,1.1630,6,5,11,1
2,0.5105,0.4258,0.0152,0.0106,0.2755,0.1685,1.0379,1.0535,1,2,3,1
3,1.9963,1.1513,0.9908,0.0245,64.7465,0.8747,1.0766,1.0526,3,2,5,1
4,0.3030,0.4040,0.0160,0.0130,0.3480,0.1680,1.0110,1.0110,2,1,3,0


In [4]:
x_data = data[['PRBUsageUL', 'PRBUsageDL', 'meanThr_DL',
       'meanThr_UL', 'maxThr_DL', 'maxThr_UL', 'meanUE_DL', 'meanUE_UL',
       'maxUE_DL', 'maxUE_UL', 'maxUE_UL+DL']]

In [5]:
y_data = data["Unusual"]

In [6]:
data["Unusual"].value_counts()

0    26721
1    10183
Name: Unusual, dtype: int64

In [7]:
x_data.shape

(36904, 11)

In [8]:
y_data.shape

(36904,)

In [9]:
y_data.head()

0    1
1    1
2    1
3    1
4    0
Name: Unusual, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size = 0.2, random_state = 1000)

In [13]:
x_train.shape

(29523, 11)

In [14]:
x_test.shape

(7381, 11)

In [15]:
x_test.shape[0] / x_data.shape[0]

0.20000541946672448

In [16]:
x_train

,PRBUsageUL,PRBUsageDL,meanThr_DL,meanThr_UL,maxThr_DL,maxThr_UL,meanUE_DL,meanUE_UL,maxUE_DL,maxUE_UL,maxUE_UL+DL
26132,9.8020,1.1120,0.2880,0.0240,10.9870,0.2940,1.0710,1.0210,3,2,5
9784,3.9410,1.0110,0.2270,0.0310,10.1730,0.5300,1.0610,1.0210,4,2,6
6170,0.4040,0.4040,0.0600,0.0130,3.6050,0.2950,1.0110,1.0110,2,1,3
29565,5.4653,0.7206,0.1686,0.0187,15.5143,0.3907,1.0390,1.0567,3,2,5
10595,1.1120,2.1220,0.4320,0.0420,19.9180,0.7560,1.1010,0.0100,3,3,6
...,...,...,...,...,...,...,...,...,...,...,...
33537,3.1330,8.9930,0.9740,0.0880,21.9590,0.6690,1.4350,0.0100,7,4,11
18782,6.7700,1.6170,0.1670,0.0430,4.5530,0.9470,1.1620,1.0510,4,3,7
3776,2.4250,17.2800,1.0550,0.0630,21.1870,0.7750,1.4350,0.0100,6,4,10
6215,9.6177,1.7333,0.4685,0.0306,30.9606,0.7054,1.1074,1.0515,5,3,8


In [17]:
from sklearn.tree import DecisionTreeClassifier

In [18]:
arb_dec_cla = DecisionTreeClassifier(criterion = "gini", splitter = "best", max_depth = 6, random_state = 1000)
arb_dec_cla.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=6, random_state=1000)

In [19]:
y_pred_adc = arb_dec_cla.predict(x_test)
y_pred_adc

array([1, 0, 1, ..., 0, 0, 0], dtype=int64)

In [20]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

print(confusion_matrix(y_pred_adc, y_test))
print(accuracy_score(y_pred_adc, y_test))
print(precision_score(y_pred_adc, y_test))
print(recall_score(y_pred_adc, y_test))
print(f1_score(y_pred_adc, y_test))
print(roc_auc_score(y_pred_adc, y_test))

[[5284  774]
 [  53 1270]]
0.887955561577022
0.6213307240704501
0.9599395313681028
0.7543807543807544
0.9160872962221828


In [21]:
(5284 + 1270)

6554

In [22]:
confusion_matrix(y_test, y_pred_adc).sum().sum()

7381

In [23]:
6554/7381

0.887955561577022

In [24]:
arb_dec_cla_2 = DecisionTreeClassifier(criterion = "entropy", splitter = "best", max_depth = 8, random_state = 1000)
arb_dec_cla_2.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=8, random_state=1000)

In [25]:
y_pred_adc_2 = arb_dec_cla_2.predict(x_test)
y_pred_adc_2

array([1, 0, 1, ..., 0, 0, 0], dtype=int64)

In [26]:
print(confusion_matrix(y_pred_adc_2, y_test))
print(accuracy_score(y_pred_adc_2, y_test))
print(precision_score(y_pred_adc_2, y_test))
print(recall_score(y_pred_adc_2, y_test))
print(f1_score(y_pred_adc_2, y_test))
print(roc_auc_score(y_pred_adc_2, y_test))

[[5271  664]
 [  66 1380]]
0.9010974122747595
0.675146771037182
0.9543568464730291
0.7908309455587393
0.9212390803553014


In [27]:
5271 + 1380

6651

In [28]:
from graphviz import Source
from sklearn.tree import export_graphviz

In [29]:
export_graphviz(
        arb_dec_cla_2,
        out_file = "arbol_2.dot",
        feature_names = x_train.columns.to_numpy(), # Nombres de las caracteristicas
        class_names = ["1", "0"], # Nombre de los grupos
        rounded = True,
        filled = True)

In [ ]:
Source.from_file("arbol_1.dot")

#### Caso 2: Regresión

In [ ]:
regresion = pd.read_csv("./Data/House_Prices_train.csv")
regresion.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,192,84,0,0,0,0,0,12,2008,250000


In [31]:
x_data = regresion[['MSSubClass', 'LotArea', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'BsmtFinSF1',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd',
       'Fireplaces', 'GarageCars', 'GarageArea', 'WoodDeckSF',
       'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea',
       'MiscVal', 'MoSold', 'YrSold']]

In [32]:
y_data = regresion["SalePrice"]

In [33]:
x0_train, x0_test, y0_train, y0_test = train_test_split(x_data, y_data, test_size = 0.2, random_state = 1000)

In [34]:
from sklearn.tree import DecisionTreeRegressor

In [35]:
arb_dec_reg = DecisionTreeRegressor(criterion = "squared_error", splitter = "best", max_depth = 9, random_state = 1000)
arb_dec_reg.fit(x0_train, y0_train)

DecisionTreeRegressor(max_depth=9, random_state=1000)

In [36]:
y0_predict_adr = arb_dec_reg.predict(x0_test)
y0_predict_adr

array([ 93826.74358974, 159815.38461538, 152414.28571429, 170713.875     ,
       139062.5       , 160224.35      , 274500.        ,  93826.74358974,
       148450.        ,  96750.        , 108194.11764706, 140000.        ,
       223500.        ,  93826.74358974, 203770.        , 129754.54545455,
       148450.        , 152414.28571429, 135905.35714286,  93826.74358974,
       124288.        , 223200.        ,  66842.85714286, 155000.        ,
       129754.54545455, 311660.        , 373279.94117647, 168833.33333333,
       151400.        , 144842.5       , 129754.54545455, 193607.3875    ,
       125500.        , 203770.        , 193607.3875    , 137893.10344828,
       129754.54545455, 306000.        , 270000.        , 148450.        ,
       129754.54545455, 148450.        ,  93826.74358974, 290000.        ,
       193607.3875    , 129754.54545455, 234539.33333333, 437154.        ,
       129754.54545455, 120650.        , 101392.70588235, 311660.        ,
       117291.51851852, 1

In [37]:
from sklearn.metrics import mean_squared_error

In [38]:
mean_squared_error(y0_test, y0_predict_adr)

1704899768.3071747

In [39]:
arb_dec_reg_2 = DecisionTreeRegressor(criterion = "friedman_mse", splitter = "random", max_depth = 9, random_state = 1000)
arb_dec_reg_2.fit(x0_train, y0_train)

DecisionTreeRegressor(criterion='friedman_mse', max_depth=9, random_state=1000,
                      splitter='random')

In [40]:
y0_predict_adr_2 = arb_dec_reg_2.predict(x0_test)
y0_predict_adr_2

array([119403.        , 160167.125     , 188700.        , 180296.16666667,
       149095.37037037, 150000.        , 248750.        , 136101.08695652,
       125833.33333333, 153000.        , 149095.37037037, 132330.        ,
       318061.        ,  97987.5       , 225893.19148936, 119403.        ,
       123500.        , 158160.71428571, 159916.66666667,  97987.5       ,
       119403.        , 174273.80952381,  81322.22222222, 180296.16666667,
       119403.        , 245707.95      , 388523.76923077, 149095.37037037,
       200100.        , 132330.        , 119403.        , 194528.21428571,
       137766.91176471, 225893.19148936, 180296.16666667, 147388.88888889,
       119403.        , 313996.23529412, 280000.        , 197500.        ,
       119403.        , 149095.37037037, 149095.37037037, 412500.        ,
       180296.16666667, 119403.        , 225893.19148936, 315000.        ,
       119403.        , 101000.        ,  95616.66666667, 444552.        ,
       119403.        , 1

In [41]:
mean_squared_error(y0_test, y0_predict_adr_2)

1426766686.8420389

In [42]:
mean_squared_error(y0_test, y0_predict_adr) # Primer modelo (mse)

1704899768.3071747

In [43]:
mean_squared_error(y0_test, y0_predict_adr_2) # Segundo modelo (friedman mse)

1426766686.8420389